# Generated by Django 3.1.5 on 2021-01-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branches',
            table='myapi_branches',
        ),
    ]
